from dto.Stats import Stats


class OverallStats:
    def __init__(self, stats: Stats):
        self._stats = stats
        if stats:
            self.totalGames = 1
            self.neutralMinionsKilledTeamJungle = self._stats.neutralMinionsKilledEnemyJungle
            self.visionScore = self._stats.visionScore
            self.magicDamageDealtToChampions = self._stats.magicDamageDealtToChampions
            self.largestMultiKill = self._stats.largestMultiKill
            self.totalTimeCrowdControlDealt = self._stats.totalTimeCrowdControlDealt
            self.longestTimeSpentLiving = self._stats.longestTimeSpentLiving
            self.tripleKills = self._stats.tripleKills
            self.playerScore9 = self._stats.playerScore9
            self.playerScore8 = self._stats.playerScore8
            self.kills = self._stats.kills
            self.playerScore1 = self._stats.playerScore1
            self.playerScore0 = self._stats.playerScore0
            self.playerScore3 = self._stats.playerScore3
            self.playerScore2 = self._stats.playerScore2
            self.playerScore5 = self._stats.playerScore5
            self.playerScore4 = self._stats.playerScore4
            self.playerScore7 = self._stats.playerScore7
            self.playerScore6 = self._stats.playerScore6
            self.totalScoreRank = self._stats.totalScoreRank
            self.neutralMinionsKilled = self._stats.neutralMinionsKilled
            self.damageDealtToTurrets = self._stats.damageDealtToTurrets
            self.physicalDamageDealtToChampions = self._stats.physicalDamageDealtToChampions
            self.damageDealtToObjectives = self._stats.damageDealtToObjectives
            self.totalUnitsHealed = self._stats.totalUnitsHealed
            self.totalDamageTaken = self._stats.totalDamageTaken
            self.wardsKilled = self._stats.wardsKilled
            self.largestCriticalStrike = self._stats.largestCriticalStrike
            self.largestKillingSpree = self._stats.largestKillingSpree
            self.quadraKills = self._stats.quadraKills
            self.magicDamageDealt = self._stats.magicDamageDealt
            self.firstBloodAssist = self._stats.firstBloodAssist
            self.item2 = self._stats.item2
            self.item3 = self._stats.item3
            self.item0 = self._stats.item0
            self.item1 = self._stats.item1
            self.item6 = self._stats.item6
            self.item4 = self._stats.item4
            self.item5 = self._stats.item5
            self.damageSelfMitigated = self._stats.damageSelfMitigated
            self.magicalDamageTaken = self._stats.magicalDamageTaken
            self.trueDamageTaken = self._stats.trueDamageTaken
            self.assists = self._stats.assists
            self.goldSpent = self._stats.goldSpent
            self.trueDamageDealt = self._stats.trueDamageDealt
            self.physicalDamageDealt = self._stats.physicalDamageDealt
            self.sightWardsBoughtInGame = self._stats.sightWardsBoughtInGame
            self.totalDamageDealtToChampions = self._stats.totalDamageDealtToChampions
            self.physicalDamageTaken = self._stats.physicalDamageTaken
            self.totalPlayerScore = self._stats.totalPlayerScore
            self.win = self._stats.win
            self.objectivePlayerScore = self._stats.objectivePlayerScore
            self.totalDamageDealt = self._stats.totalDamageDealt
            self.neutralMinionsKilledEnemyJungle = self._stats.neutralMinionsKilledEnemyJungle
            self.deaths = self._stats.deaths
            self.wardsPlaced = self._stats.wardsPlaced
            self.turretKills = self._stats.turretKills
            self.firstBloodKill = self._stats.firstBloodKill
            self.trueDamageDealtToChampions = self._stats.trueDamageDealtToChampions
            self.goldEarned = self._stats.goldEarned
            self.killingSprees = self._stats.killingSprees
            self.unrealKills = self._stats.unrealKills
            self.champLevel = self._stats.champLevel
            self.doubleKills = self._stats.doubleKills
            self.inhibitorKills = self._stats.inhibitorKills
            self.combatPlayerScore = self._stats.combatPlayerScore
            self.visionWardsBoughtInGame = self._stats.visionWardsBoughtInGame
            self.pentaKills = self._stats.pentaKills
            self.totalHeal = self._stats.totalHeal
            self.totalMinionsKilled = self._stats.totalMinionsKilled
            self.timeCCingOthers = self._stats.timeCCingOthers

    def __add__(self, other: Stats):
        self.totalGames += 1
        self.neutralMinionsKilledTeamJungle += self._stats.neutralMinionsKilledEnemyJungle
        self.visionScore += self._stats.visionScore
        self.magicDamageDealtToChampions += self._stats.magicDamageDealtToChampions
        self.largestMultiKill = max(self._stats.largestMultiKill, self.largestMultiKill)
        self.totalTimeCrowdControlDealt += self._stats.totalTimeCrowdControlDealt
        self.longestTimeSpentLiving = max(self._stats.longestTimeSpentLiving, self.longestTimeSpentLiving)
        self.tripleKills += self._stats.tripleKills
        self.playerScore9 += self._stats.playerScore9
        self.playerScore8 += self._stats.playerScore8
        self.kills += self._stats.kills
        self.playerScore1 += self._stats.playerScore1
        self.playerScore0 += self._stats.playerScore0
        self.playerScore3 += self._stats.playerScore3
        self.playerScore2 += self._stats.playerScore2
        self.playerScore5 += self._stats.playerScore5
        self.playerScore4 += self._stats.playerScore4
        self.playerScore7 += self._stats.playerScore7
        self.playerScore6 += self._stats.playerScore6
        self.totalScoreRank += self._stats.totalScoreRank
        self.neutralMinionsKilled += self._stats.neutralMinionsKilled
        self.damageDealtToTurrets += self._stats.damageDealtToTurrets
        self.physicalDamageDealtToChampions += self._stats.physicalDamageDealtToChampions
        self.damageDealtToObjectives += self._stats.damageDealtToObjectives
        self.totalUnitsHealed += self._stats.totalUnitsHealed
        self.totalDamageTaken += self._stats.totalDamageTaken
        self.wardsKilled += self._stats.wardsKilled
        self.largestCriticalStrike = max(self._stats.largestCriticalStrike, self.largestCriticalStrike)
        self.largestKillingSpree = max(self._stats.largestKillingSpree, self.largestKillingSpree)
        self.quadraKills += self._stats.quadraKills
        self.magicDamageDealt += self._stats.magicDamageDealt
        self.firstBloodAssist += self._stats.firstBloodAssist
        self.damageSelfMitigated += self._stats.damageSelfMitigated
        self.magicalDamageTaken += self._stats.magicalDamageTaken
        self.trueDamageTaken += self._stats.trueDamageTaken
        self.assists += self._stats.assists
        self.goldSpent += self._stats.goldSpent
        self.trueDamageDealt += self._stats.trueDamageDealt
        self.physicalDamageDealt += self._stats.physicalDamageDealt
        self.sightWardsBoughtInGame += self._stats.sightWardsBoughtInGame
        self.totalDamageDealtToChampions += self._stats.totalDamageDealtToChampions
        self.physicalDamageTaken += self._stats.physicalDamageTaken
        self.totalPlayerScore += self._stats.totalPlayerScore
        self.win += self._stats.win
        self.objectivePlayerScore += self._stats.objectivePlayerScore
        self.totalDamageDealt += self._stats.totalDamageDealt
        self.neutralMinionsKilledEnemyJungle += self._stats.neutralMinionsKilledEnemyJungle
        self.deaths += self._stats.deaths
        self.wardsPlaced += self._stats.wardsPlaced
        self.turretKills += self._stats.turretKills
        self.firstBloodKill += self._stats.firstBloodKill
        self.trueDamageDealtToChampions += self._stats.trueDamageDealtToChampions
        self.goldEarned += self._stats.goldEarned
        self.killingSprees += self._stats.killingSprees
        self.unrealKills += self._stats.unrealKills
        self.champLevel += self._stats.champLevel
        self.doubleKills += self._stats.doubleKills
        self.inhibitorKills += self._stats.inhibitorKills
        self.combatPlayerScore += self._stats.combatPlayerScore
        self.visionWardsBoughtInGame += self._stats.visionWardsBoughtInGame
        self.pentaKills += self._stats.pentaKills
        self.totalHeal += self._stats.totalHeal
        self.totalMinionsKilled += self._stats.totalMinionsKilled
        self.timeCCingOthers += self._stats.timeCCingOthers

    def finalize(self):
        self.avgNeutralMinionsKilledTeamJungle = self.neutralMinionsKilledEnemyJungle / self.totalGames
        self.avgVisionScore = self.visionScore / self.totalGames
        self.avgMagicDamageDealtToChampions = self.magicDamageDealtToChampions / self.totalGames
        self.avgLargestMultiKill = self.largestMultiKill / self.totalGames
        self.avgTotalTimeCrowdControlDealt = self.totalTimeCrowdControlDealt / self.totalGames
        self.avgLongestTimeSpentLiving = self.longestTimeSpentLiving / self.totalGames
        self.avgTripleKills = self.tripleKills / self.totalGames
        self.avgPlayerScore9 = self.playerScore9 / self.totalGames
        self.avgPlayerScore8 = self.playerScore8 / self.totalGames
        self.avgKills = self.kills / self.totalGames
        self.avgPlayerScore1 = self.playerScore1 / self.totalGames
        self.avgPlayerScore0 = self.playerScore0 / self.totalGames
        self.avgPlayerScore3 = self.playerScore3 / self.totalGames
        self.avgPlayerScore2 = self.playerScore2 / self.totalGames
        self.avgPlayerScore5 = self.playerScore5 / self.totalGames
        self.avgPlayerScore4 = self.playerScore4 / self.totalGames
        self.avgPlayerScore7 = self.playerScore7 / self.totalGames
        self.avgPlayerScore6 = self.playerScore6 / self.totalGames
        self.avgTotalScoreRank = self.totalScoreRank / self.totalGames
        self.avgNeutralMinionsKilled = self.neutralMinionsKilled / self.totalGames
        self.avgDamageDealtToTurrets = self.damageDealtToTurrets / self.totalGames
        self.avgPhysicalDamageDealtToChampions = self.physicalDamageDealtToChampions / self.totalGames
        self.avgDamageDealtToObjectives = self.damageDealtToObjectives / self.totalGames
        self.avgTotalUnitsHealed = self.totalUnitsHealed / self.totalGames
        self.avgTotalDamageTaken = self.totalDamageTaken / self.totalGames
        self.avgWardsKilled = self.wardsKilled / self.totalGames
        self.avgLargestCriticalStrike = self.largestCriticalStrike / self.totalGames
        self.avgLargestKillingSpree = self.largestKillingSpree / self.totalGames
        self.avgQuadraKills = self.quadraKills / self.totalGames
        self.avgMagicDamageDealt = self.magicDamageDealt / self.totalGames
        self.avgFirstBloodAssist = self.firstBloodAssist / self.totalGames
        self.avgItem2 = self.item2 / self.totalGames
        self.avgItem3 = self.item3 / self.totalGames
        self.avgItem0 = self.item0 / self.totalGames
        self.avgItem1 = self.item1 / self.totalGames
        self.avgItem6 = self.item6 / self.totalGames
        self.avgItem4 = self.item4 / self.totalGames
        self.avgItem5 = self.item5 / self.totalGames
        self.avgDamageSelfMitigated = self.damageSelfMitigated / self.totalGames
        self.avgMagicalDamageTaken = self.magicalDamageTaken / self.totalGames
        self.avgTrueDamageTaken = self.trueDamageTaken / self.totalGames
        self.avgAssists = self.assists / self.totalGames
        self.avgGoldSpent = self.goldSpent / self.totalGames
        self.avgTrueDamageDealt = self.trueDamageDealt / self.totalGames
        self.avgPhysicalDamageDealt = self.physicalDamageDealt
        self.avgSightWardsBoughtInGame = self.sightWardsBoughtInGame / self.totalGames
        self.avgTotalDamageDealtToChampions = self.totalDamageDealtToChampions / self.totalGames
        self.avgPhysicalDamageTaken = self.physicalDamageTaken / self.totalGames
        self.avgTotalPlayerScore = self.totalPlayerScore / self.totalGames
        self.avgWin = self.win / self.totalGames
        self.avgObjectivePlayerScore = self.objectivePlayerScore / self.totalGames
        self.avgTotalDamageDealt = self.totalDamageDealt / self.totalGames
        self.avgNeutralMinionsKilledEnemyJungle = self.neutralMinionsKilledEnemyJungle / self.totalGames
        self.avgDeaths = self.deaths / self.totalGames
        self.avgWardsPlaced = self.wardsPlaced / self.totalGames
        self.avgTurretKills = self.turretKills / self.totalGames
        self.avgFirstBloodKill = self.firstBloodKill / self.totalGames
        self.avgTrueDamageDealtToChampions = self.trueDamageDealtToChampions / self.totalGames
        self.avgGoldEarned = self.goldEarned / self.totalGames
        self.avgKillingSprees = self.killingSprees / self.totalGames
        self.avgUnrealKills = self.unrealKills / self.totalGames
        self.avgChampLevel = self.champLevel / self.totalGames
        self.avgDoubleKills = self.doubleKills / self.totalGames
        self.avgInhibitorKills = self.inhibitorKills / self.totalGames
        self.avgCombatPlayerScore = self.combatPlayerScore / self.totalGames
        self.avgVisionWardsBoughtInGame = self.visionWardsBoughtInGame / self.totalGames
        self.avgPentaKills = self.pentaKills / self.totalGames
        self.avgTotalHeal = self.totalHeal / self.totalGames
        self.avgTotalMinionsKilled = self.totalMinionsKilled / self.totalGames
        self.avgTimeCCingOthers = self.timeCCingOthers / self.totalGames
